--- 
  aws_access_key_id: AKIAJAOQIYXAI4XDBG7A
  aws_secret_access_key: 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
  web_service_host: localhost
  web_service_port: 9090
  web_service_handler: thin
  sqs_queue_name: tranz_testing
